# -*- coding: utf-8 -*-
"""App_Shorten.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S68d4H78AsS-y_C56S1l4UxWqiRxQABl

# ***APP ACORTADOR DE ENLACES PERSONALIZADO***
"""

import streamlit as st
import requests

# Función para acortar URL usando TinyURL
def shorten_url_tinyurl(original_url, custom_name):
    base_url = "https://api.tinyurl.com/create"
    headers = {
        "Authorization": "2x8qBy8YFzXRGY8YbgsC4URfOgito3IEaRMn7vO84gOyYfr6uo2W3yqRJtqN",
        "Content-Type": "application/json"
    }
    payload = {
        "url": original_url,
        "domain": "tinyurl.com",
        "alias": custom_name
    }
    response = requests.post(base_url, headers=headers, json=payload)
    
    try:
        response_data = response.json()
    except ValueError:
        return None, "Error al procesar la respuesta de la API"

    if isinstance(response_data, dict):
        if response.status_code == 201:
            return response_data["data"]["tiny_url"], None
        else:
            return None, response_data.get("errors", [{"message": "Error desconocido"}])[0]["message"]
    else:
        return None, "Respuesta inesperada de la API"

# Configuración de la página
st.set_page_config(page_title="Acortador de Enlaces Personalizado", page_icon=":link:")

# Título y logo
st.title("Acortador de Enlaces Personalizado")
st.image("https://elnuevoempresario.com/wp-content/uploads/2019/04/acortar-url.-herramientas-para-acortar-enlaces.jpg", width=100)

# Entrada de URL original
original_url = st.text_input("Ingresa la URL original:")
st.write("Original URL:", original_url)  # Mostrar la URL original para depuración

# Entrada de nombre personalizado
custom_name = st.text_input("Ingresa el nombre personalizado para la URL:")
st.write("Custom Name:", custom_name)  # Mostrar el nombre personalizado para depuración

# Botón para acortar URL
if st.button("Acortar URL"):
    if original_url and custom_name:
        shortened_url, error_message = shorten_url_tinyurl(original_url, custom_name)
        if shortened_url:
            st.success(f"URL acortada y personalizada: {shortened_url}")
        else:
            st.error(f"Error al acortar la URL: {error_message}")
    else:
        st.warning("Por favor, ingresa tanto la URL original como el nombre personalizado.")

# Pie de página con información del desarrollador
st.markdown("""
---
**Desarrollador:** Edwin Quintero Alzate
**Email:** egqa1975@gmail.com
**LinkedIn:** https://www.linkedin.com/in/edwinquintero0329/
**GitHub:** https://github.com/Edwin1719
""")
